apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: "[[account_name]]-[[region_prefix]]-prod"
spec:
  template:
    metadata:
      labels:
        managed-by: karpenter
        workload-type: application
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: "[[account_name]]-[[region_prefix]]-shared"
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values: [ "on-demand", "spot" ]
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values: [ "c", "m", "r" ]
      - key: kubernetes.io/arch
        operator: In
        values: [ "amd64" ]
      - key: topology.kubernetes.io/zone
        operator: Exists
        minValues: 3
  limits:
    cpu: "1000"
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
